"use client";

import { Howl, Howler } from "howler";

Howler.autoSuspend = false;

const HOVER_COUNT = 10;

// Generated by scripts/generate-sounds.mjs — do not edit by hand
const SPRITES: Record<string, [number, number]> = {
  hover1:  [0, 500],
  hover2:  [580, 500],
  hover3:  [1160, 500],
  hover4:  [1740, 500],
  hover5:  [2320, 500],
  hover6:  [2900, 500],
  hover7:  [3480, 500],
  hover8:  [4060, 500],
  hover9:  [4640, 500],
  hover10: [5220, 500],
  click:   [5800, 300],
  whoosh:  [6180, 700],
  toggle:  [6960, 200],
};

let howl: Howl | null = null;
let hoverIndex = 0;
let contextUnlocked = false;

function getHowl(): Howl {
  if (!howl) {
    howl = new Howl({
      src: ["/audio/ui-sprites.mp3"],
      sprite: SPRITES,
      volume: 0.55,
      pool: 15,
      preload: true,
    });
  }
  return howl;
}

const STORAGE_KEY = "sound-enabled";

function prefersReducedMotion(): boolean {
  if (typeof window === "undefined") return false;
  return window.matchMedia("(prefers-reduced-motion: reduce)").matches;
}

function isTouchDevice(): boolean {
  if (typeof window === "undefined") return false;
  return window.matchMedia("(pointer: coarse)").matches;
}

/** True at lg+ viewport on a non-touch device with no reduced motion.
 *  Matches the SoundToggle visibility (inside Navbar's `hidden lg:flex`). */
export function isSoundAvailable(): boolean {
  if (typeof window === "undefined") return false;
  if (isTouchDevice()) return false;
  if (prefersReducedMotion()) return false;
  if (!window.matchMedia("(min-width: 1024px)").matches) return false;
  return true;
}

export function isSoundEnabled(): boolean {
  if (!isSoundAvailable()) return false;
  return localStorage.getItem(STORAGE_KEY) === "true";
}

/** Pre-load audio when sound was enabled in a previous session.
 *  Installs a one-time pointerdown/keydown listener to unlock AudioContext.
 *  Browsers only allow AudioContext.resume() from user-activation events
 *  (click, pointerdown, keydown) — hover/mousemove do NOT count.
 *  We use pointerdown because it fires BEFORE click, so the context
 *  is already running by the time any handler runs. */
export function initSound() {
  if (!isSoundAvailable()) return;
  if (!isSoundEnabled()) return;
  getHowl(); // preload audio sprite

  if (contextUnlocked) return;

  const unlock = () => {
    contextUnlocked = true;
    Howler.ctx?.resume();
    window.removeEventListener("pointerdown", unlock, true);
    window.removeEventListener("keydown", unlock, true);
  };
  // Capture phase — fires before any component handler
  window.addEventListener("pointerdown", unlock, true);
  window.addEventListener("keydown", unlock, true);
}

export function toggleSound(): boolean {
  if (!isSoundAvailable()) return false;
  const next = !isSoundEnabled();

  const h = getHowl();

  // Click handler — safe to unlock AudioContext
  contextUnlocked = true;
  Howler.ctx?.resume();

  // Play toggle sound BEFORE writing state so disable path still has access
  if (h.state() === "loaded") {
    h.play("toggle");
  } else if (next) {
    h.once("load", () => h.play("toggle"));
  }

  localStorage.setItem(STORAGE_KEY, String(next));
  return next;
}

/** Play the next Runaway piano note. Notes overlap (sustain pedal). */
export function playHoverSound() {
  if (!isSoundAvailable()) return;
  if (!isSoundEnabled()) return;
  // Hover is NOT a user-activation event — if context isn't unlocked yet,
  // the browser will silently ignore play(). Skip to avoid queueing.
  if (!contextUnlocked) return;
  if (!howl || howl.state() !== "loaded") return;

  hoverIndex = (hoverIndex % HOVER_COUNT) + 1;
  howl.play(`hover${hoverIndex}`);
}
